services:
  nginx:
    build: requirements/nginx/.
    restart: unless-stopped
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./home/jsobreir/data/web:/var/www/html
    networks:
      inception:
  wordpress:
    build: requirements/wordpress/.
    restart: unless-stopped
    container_name: wp-php
    env_file:
      - ../.env
    volumes:
      - ./home/jsobreir/data/web:/var/www/html
    networks:
      inception:
    secrets:
      - db_root_password
      - db_password
  mariadb:
    build: requirements/mariadb/.
    restart: unless-stopped
    container_name: mariadb
    volumes:
      - ./home/jsobreir/data/database:/var/lib/mysql
    networks:
      inception:
    secrets:
      - db_root_password
      - db_password

networks:
  inception:

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
